version: "3.8"

services:
  backend:
    build: ./backend
    container_name: fusionpact-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 6000 --reload
    ports:
      - "6000:6000"
    volumes:
      - ./backend:/app
    networks:
      - fusionnet

  frontend:
    build: ./frontend
    container_name: fusionpact-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fusionnet

volumes:
  backend_data:

networks:
  fusionnet:
